version: "3.8"

services:
  # =========================
  # Mandatory services
  # =========================

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis   # still depends on it if you're using Redis cache
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception

  # =========================
  # Bonus services
  # =========================

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "6379"

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
      
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - adminer_data:/var/www/html

  adminer-nginx:
    build:
      context: ./requirements/bonus/adminer-nginx
      dockerfile: Dockerfile
    container_name: adminer-nginx
    restart: unless-stopped
    depends_on:
      - adminer
    ports:
      - "8080:80"
    networks:
      - inception
    volumes:
      - adminer_data:/var/www/html:ro
  
  static-website:
    build:
      context: ./requirements/bonus/static-website
      dockerfile: Dockerfile
    container_name: static-website
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - inception

  portainer:
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception

  filebrowser:
    build:
      context: ./requirements/bonus/filebrowser
      dockerfile: Dockerfile
    container_name: filebrowser
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8080"
    volumes:
      - filebrowser_data:/data
      - wordpress_data:/srv
    networks:
      - inception


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aayache/data/mariadb

  filebrowser_data:
    driver: local
  
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aayache/data/wordpress

  portainer_data:
    driver: local
 
  adminer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aayache/data/adminer



networks:
  inception:
    driver: bridge
