# listen=YES
# listen_ipv6=NO
# listen_port=21
# background=NO

# anonymous_enable=NO
# local_enable=YES
# write_enable=YES
# local_umask=022

# # Chroot users to their root (recommended)
# chroot_local_user=YES
# allow_writeable_chroot=YES

# # WordPress directory as FTP root
# local_root=/var/www/html

# pasv_address=0.0.0.0

# # Passive mode (match your compose ports)
# pasv_enable=YES
# pasv_min_port=21100
# pasv_max_port=21110

# # IMPORTANT: set this to your VM/host IP (or your domain), NOT 0.0.0.0
# # Example: pasv_address=192.168.1.50
# pasv_addr_resolve=NO

# # Logging
# xferlog_enable=YES
# log_ftp_protocol=YES
# vsftpd_log_file=/var/log/vsftpd.log

# # Alpine PAM service name (usually vsftpd)
# pam_service_name=vsftpd

# # Docker seccomp sometimes breaks vsftpd (optional)
# seccomp_sandbox=NO



listen=YES
listen_port=21
background=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=0.0.0.0